{
 "title": "Dash3Items",
 "tags": [
  "iot",
  "sensores"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "device_name",
    "label": "Estação",
    "query": "SELECT DISTINCT device_name FROM sensor_data ORDER BY device_name ASC;"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "(SELECT 'Dados da estação ' || device_name || ' as ' || TO_CHAR(time_aq, 'HH24:MI:SS DD/MM/YYYY') AS value FROM sensor_data WHERE device_name = '${device_name}' ORDER BY time_aq DESC LIMIT 1)\nUNION\n(SELECT 'Selecione uma Estação'  AS value WHERE NOT EXISTS (SELECT 1 FROM sensor_data WHERE device_name = '${device_name}'));"
    }
   ]
  },
  {
   "title": "Temperatura (°C)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT temp_p AS value FROM sensor_data WHERE device_name = '${device_name}' ORDER BY time_aq DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Umidade (%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT humi AS value FROM sensor_data WHERE device_name = '${device_name}' ORDER BY time_aq DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Pressão Atmosférica (hPa)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT press AS value FROM sensor_data WHERE device_name = '${device_name}' ORDER BY time_aq DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Temperaturas (°C) - Hoje",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MIN(temp_p) AS \"Mínima\", MAX(temp_p) AS \"Máxima\" FROM sensor_data WHERE time_aq::date = CURRENT_DATE AND device_name = '${device_name}';"
    }
   ]
  },
  {
   "title": "Mapa das estações",
   "type": "geomap",
   "description": "Mostra a posição geográfica das estações",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT device_name, lat, lon FROM sensor_data WHERE device_name = '${device_name}';"
    }
   ]
  },
  {
   "title": "Temperaturas (°C) - Média dos últimos 7 dias",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ROUND(AVG(min_temp)::numeric,1) AS \"Média Mínima\", ROUND(AVG(max_temp)::numeric,1) AS \"Média Máxima\" FROM ( SELECT date_trunc('day', time_aq)::date AS dia, MAX(temp_p) AS max_temp, MIN(temp_p) AS min_temp FROM sensor_data WHERE time_aq >= NOW() - INTERVAL '7 days' AND device_name = '${device_name}' GROUP BY dia ) t;"
    }
   ]
  },
  {
   "title": "Máximos e Mínimos Diários de Temperatura (°C), Umidade (%) e Pressão Atmosférica (hPa)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', time_aq) AS time,\n  MAX(temp_p) AS \"Temperatura Máxima\",\n  MIN(temp_p) AS \"Temperatura Mínima\",\n  MAX(humi) AS \"Umidade Máxima\",\n  MIN(humi) AS \"Umidade Mínima\",\n  MAX(press) AS \"Pressão Atmosférica Máxima\",\n  MIN(press) AS \"Pressão Atmosférica Mínima\"\nFROM sensor_data\nWHERE\n  $__timeFilter(time_aq) AND device_name = '${device_name}' \nGROUP BY 1\nORDER BY 1 ASC;"
    }
   ]
  }
 ]
}