{
 "title": "Dash4Items",
 "tags": [
  "iot",
  "sensores"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "device_name",
    "label": "Estação",
    "query": "SELECT DISTINCT device_name FROM sensor_data ORDER BY device_name ASC;"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "(SELECT 'Dados da estação ' || device_name || ' as ' || TO_CHAR(time_aq, 'HH24:MI:SS DD/MM/YYYY') AS value FROM sensor_data WHERE device_name = '${device_name}' ORDER BY time_aq DESC LIMIT 1)\nUNION\n(SELECT 'Selecione uma Estação'  AS value WHERE NOT EXISTS (SELECT 1 FROM sensor_data WHERE device_name = '${device_name}'));"
    }
   ]
  },
  {
   "title": "Mapa das estações",
   "type": "geomap",
   "description": "Mostra a posição geográfica das estações",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT device_name, lat, lon FROM sensor_data WHERE device_name = '${device_name}';"
    }
   ]
  },
  {
   "title": "Temperatura (°C)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT temp_p AS value FROM sensor_data WHERE device_name = '${device_name}' ORDER BY time_aq DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Umidade (%)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT humi AS value FROM sensor_data WHERE device_name = '${device_name}' ORDER BY time_aq DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Pressão Atmosférica (hPa)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT press AS value FROM sensor_data WHERE device_name = '${device_name}' ORDER BY time_aq DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Luminosidade (Lux)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT lumi AS value FROM sensor_data WHERE device_name = '${device_name}' ORDER BY time_aq DESC LIMIT 1;"
    }
   ]
  }
 ]
}